version: '3'
services:

  # The core platform, mounts docker control socket and route definition into the image
  video-list-consumer-core:
    image: farmstack/trusted-connector:${EXAMPLE_TAG:-latest}
    tty: true
    stdin_open: true
    volumes:
      - ./logs/consumer/:/root/log/
      - /var/run/docker.sock:/var/run/docker.sock
      - ./cert-store/consumer-keystore.p12:/root/etc/consumer-keystore.p12
      - ./cert-store/truststore.p12:/root/etc/truststore.p12
      - ./video-list-request-routes.xml:/root/deploy/video-list-request-routes.xml
      - ./etc/settings2.mapdb:/root/etc/settings.mapdb
      - ./deploy/allow-all-flows.pl:/root/deploy/allow-all-flows.pl

    # Uncomment to run the provider & consumer nodes on separate server
    # replace x.x.x.x with the provider ip address
    extra_hosts:
      - "provider-core:34.136.125.81"

    # Enable this port mappings for debugging or UI access from localhost
    ports:
    # Enable this port mapping (along with "ports:" above) to allow access to IDSCP from outside the ids-wide network
      - "29292:29292"
    # Using two networks ids-wide and consumer-internal for external comunication and internal communication, respectively
    networks:
      ids-wide:
        aliases:
          - consumer-core
      video-consumer-internal:


    # The core platform, mounts docker control socket and route definition into the image
  video-list-provider-core:
    image: farmstack/trusted-connector:${EXAMPLE_TAG:-latest}
    tty: true
    stdin_open: true
    volumes:
      - ./logs/provider/:/root/log/
      - /var/run/docker.sock:/var/run/docker.sock
      - ./cert-store/provider-keystore.p12:/root/etc/provider-keystore.p12
      - ./cert-store/truststore.p12:/root/etc/truststore.p12
      - ./location-response-routes.xml:/root/deploy/location-response-routes.xml
      - ./etc/settings4.mapdb:/root/etc/settings.mapdb
      - ./deploy/allow-all-flows.pl:/root/deploy/allow-all-flows.pl

    # Uncomment to run the provider & consumer nodes on separate server
    # replace x.x.x.x with the consumer ip address
    extra_hosts:
      - "consumer-core:34.136.125.81"

    ports:
      - 8990:8989

    # Using two networks ids-wide and provider-internal for external comunication and internal communication respectively
    networks:
      ids-wide2:
        aliases:
          - provider-core
      video-provider-internal:
    depends_on:
      - video-list-consumer-core


  # Data App (REST consumer, displays web page)
  video-list-app-fao:
    image: farmstack/video-list-app-fao:restapi
    env_file:
      - ../video-list-app/.env
    ports:
      - "3002:3002"
    networks:
      - video-consumer-internal
      - video-provider-internal

networks:
  ids-wide:
    driver: bridge
  ids-wide2:
    driver: bridge
  video-consumer-internal:
    driver: bridge
  video-provider-internal:
    driver: bridge