version: '3'
services:

  # The core platform, mounts docker control socket and route definition into the image
  provider-core:
    image: farmstack/trusted-connector:1.0.0
    tty: true
    stdin_open: true
    volumes:
      - ./logs/provider/:/root/log/
      - /var/run/docker.sock:/var/run/docker.sock
      - ./cert-store/provider-keystore.p12:/root/etc/provider-keystore.p12
      - ./cert-store/truststore.p12:/root/etc/truststore.p12
      - ./location-request-routes.xml:/root/deploy/location-request-routes.xml
      - ./etc/settings.mapdb:/root/etc/settings.mapdb
      - ./deploy/allow-all-flows.pl:/root/deploy/allow-all-flows.pl

    ports:
      - 8989:8989

    # Using two networks ids-wide and provider-internal for external comunication and internal communication respectively
    networks:
      ids-wide:
        aliases:
          - provider-core
      location-provider-internal:


  provider-app:
    image: farmstack/location-app-fao:restapi
    ports:
      - 3001:3001
    networks:
      - location-provider-internal
      - location-consumer-internal

networks:
  ids-wide:
    driver: bridge
  ids-wide2:
    driver: bridge
  location-provider-internal:
    driver: bridge
  location-consumer-internal:
    driver: bridge